# before:
#   hooks:
#   - ./scripts/completions.sh
builds:
- binary: akslifecycle
  main: ./
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0
  # ldflags:
  # - -s -w -X github.com/muandane/akslifecycle/cmd.version={{.Version}}

release:
  prerelease: auto

universal_binaries:
- replace: true

archives:
- name_template: >-
    {{- .ProjectName }}_ {{- .Version }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end -}}
  format_overrides:
  - goos: windows
    format: zip
  builds_info:
    group: root
    owner: root
  files:
  - README.md
  - LICENSE

checksum:
  name_template: 'checksums.txt'

dockers:
- use: buildx
  goos: linux
  goarch: amd64
  image_templates:
  - "simplifi-ed/{{ .ProjectName }}:{{ .Version }}-amd64"
  - "simplifi-ed/{{ .ProjectName }}:latest-amd64"
  build_flag_templates:
  - "--platform=linux/amd64"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  extra_files:
  - go.mod
  - go.sum
  - utils/lifecycle/startNode.go
  - utils/lifecycle/stopNode.go
  - internal/azure.go
  - cmd/root.go
  - main.go
- use: buildx
  goos: linux
  goarch: arm64
  image_templates:
  - "simplifi-ed/{{ .ProjectName }}:{{ .Version }}-armv64"
  - "simplifi-ed/{{ .ProjectName }}:latest-armv7"
  build_flag_templates:
  - "--platform=linux/arm64"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  extra_files:
  - go.mod
  - go.sum
  - utils/lifecycle/startNode.go
  - utils/lifecycle/stopNode.go
  - internal/azure.go
  - cmd/root.go
  - main.go
docker_manifests:
- name_template: simplifi-ed/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - simplifi-ed/{{ .ProjectName }}:{{ .Version }}-amd64
  - simplifi-ed/{{ .ProjectName }}:{{ .Version }}-armv64
- name_template: simplifi-ed/{{ .ProjectName }}:latest
  image_templates:
  - simplifi-ed/{{ .ProjectName }}:latest-amd64
  - simplifi-ed/{{ .ProjectName }}:latest-armv64

snapshot:
  name_template: "{{ incpatch .Version }}-SNAPSHOT"

source:
  enabled: true
