resources:
- ResourceGroupName: rg-caas-dev-blue
  ClusterName: aks-caas-dev-blue
  nodePools:
  - bluew
  - caasdev97523
  startSchedule: "2 14 * * 1-5"
  stopSchedule: "14 14 * * 1-5"
- ResourceGroupName: rg-caas-dev-green
  ClusterName: aks-caas-dev-green
  nodePools:
  - greenw
  - caasdev0d860
  startSchedule: "2 14 * * 1-5"
  stopSchedule: "14 14 * * 1-5"
