name: goreleaser

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Check out code 
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PUBLISHER_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.21.5'
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}